#20241128(20.28)
#15486.selmastern.1weektask
#
###########################
library(rvest)
library(xml2)
library(httr)
x<-GET("https://www.gesetze-im-internet.de/begdv_6/anlage.html")
res<-content(x,"raw")
?content
htm<-read_html("list_cc.html")
#htm<-read_html(r)
cc.df<-html_table(htm)
cc.df<-data.frame(cc.df[[1]])
tbody<-xml_find_all(htm,"//tbody")
all.r<-xml_find_all(tbody,"//tr")
xml_text(all.r)
library(stringi)
sz<-stri_extract_all_regex(cc.df,"[^a-zA-Z0-9)(,\n:)-.=]")
sz.u<-unique(unlist(sz))
sz.u
library(quanteda)
cc.tok.1<-tokenize_word1(cc.df$Konzentrationslager.und.AuÃ.enkommandos,)
cc.tok.2<-tokenize_word1(cc.df$Konzentrationslager.und.AuÃ.enkommandos.1,)
cc.tok.3<-tokenize_word1(cc.df$Hauptlager.der.AuÃ.enkommandos,)
cc.tok.1<-unique(unlist(cc.tok.1))
cc.tok.2<-unique(unlist(cc.tok.2))
cc.tok.3<-unique(unlist(cc.tok.3))
cc.tok.3
mö<-stri_extract_all_regex(cc.df,"\\b.+sterreich")
mÜ<-stri_extract_all_regex(cc.df,"berlingen")
mö
mÜ
sz.array<-c(
ü="Ã¼",
ö="Ã¶",
Ö="Ã\\u0096",
ß="Ã\\u009f",

)
sz.array  

###
t<-read_html("cc-cpt.html")
tb<-xml_find_all(t,"//table")  
xml_text(tb[[5]])  
cc.t.1<-html_table(tb[[1]])
cc.ns<-colnames(cc.t.1)
cc.t.2<-html_table(tb[[2]])
colnames(cc.t.2)<-cc.ns
cc.t.3<-html_table(tb[[3]])  
colnames(cc.t.3)<-cc.ns
cc.t.4<-html_table(tb[[4]])  
colnames(cc.t.4)<-cc.ns
cc.t.5<-html_table(tb[[5]])  
colnames(cc.t.5)<-cc.ns
cc.t.6<-rbind(cc.t.1,cc.t.2,cc.t.3,cc.t.4,cc.t.5)
write.csv(cc.t.6,"cc.df.csv")
cc.t.3<-rbind(cc.t.1,html_table(tb[[3]]))

cc.t.4<-rbind(cc.t.1,html_table(tb[[4]]))
cc.t.5<-rbind(cc.t.1,html_table(tb[[5]]))
cc.t.1<-rbind(cc.t.1,html_table(tb[[2]]))